bog_compressor:
  intercooler_efficiency: 0.85
  stage1:
    compression_ratio: 3.0
    design_flow_kgh: 2000
    efficiency: 0.75
    rated_power_kw: 800
  stage2:
    compression_ratio: 2.5
    design_flow_kgh: 2000
    efficiency: 0.78
    rated_power_kw: 600
control:
  export_flow_setpoint: 1000.0
  export_pressure_setpoint: 6500.0
  orv_temp_setpoint: 5.0
  recondenser_temp_setpoint: -100.0
  tank_pressure_setpoint: 120.0
environment:
  humidity_base: 70.0
  seawater_temp: 15.0
  temp_base: 25.0
  wind_speed_base: 5.0
export:
  flow_base: 1000.0
  pressure_setpoint: 6500.0
orv:
  design_capacity_tph: 50
  fouling_rate_per_day: 0.001
  initial_fouling_factor: 1.0
  seawater_flow_m3h: 8000
  tube_count: 200
  tube_diameter_m: 0.05
  tube_length_m: 12
pumps:
  booster:
    efficiency: 0.75
    npsh_required_m: 2.0
    rated_flow_m3h: 800
    rated_head_m: 50
    rated_power_kw: 200
  high_pressure:
    efficiency: 0.78
    npsh_required_m: 3.0
    rated_flow_m3h: 600
    rated_head_m: 1500
    rated_power_kw: 2500
recondenser:
  column_diameter_m: 2.0
  column_height_m: 8.0
  design_capacity_kgh: 1500
  heat_transfer_coeff: 2000
  spray_nozzle_count: 20
simulation:
  duration_days: 180
  random_seed: 2025
  start_time: '2024-01-01T00:00:00'
  time_step: 60.0
tank:
  ambient_heat_leak_factor: 1.0
  capacity_m3: 2000
  design_pressure_kPa: 150.0
  initial_level_pct: 85.0
  insulation_thickness_m: 0.3
