# LNG项目优化器默认配置
# 标准配置，适用于大多数使用场景

# 优化配置
optimization:
  # Hampel异常检测配置
  hampel_window: 15
  hampel_sigma: 3.0
  use_adaptive_hampel: true

  # GPR配置
  gpr_auto_tune: true
  gpr_validation_split: 0.2

  # 特征提取配置
  feature_window_size: 180
  feature_stride: 30

  # 缓存配置
  enable_caching: true
  cache_dir: "cache/features"
  cache_max_size_gb: 2.0

  # 并行处理配置
  enable_parallel: true
  max_workers: null  # 自动检测

  # 输出配置
  output_dir: "results"

# 验证配置
validation:
  target_metrics:
    r2_min: 0.75
    cv_rmse_max: 0.06
    nmbe_max: 0.006
    mae_max_percent: 5.0
    inference_time_per_sample_ms: 10.0

  # 验证模式配置
  enable_cross_validation: true
  cross_validation_folds: 5
  enable_stability_check: true
  enable_resource_validation: true
  enable_edge_case_testing: true

# 基准测试配置
benchmark:
  test_data_sizes: [1000, 5000, 10000]
  n_runs: 3
  enable_visualization: true
  save_detailed_results: true

# 资源监控配置
monitoring:
  enable_resource_monitoring: true
  monitoring_interval: 0.5
  memory_threshold_percent: 85
  cpu_threshold_percent: 90
  enable_alerts: true

# 日志配置
logging:
  level: "INFO"
  save_logs: true
  log_dir: "logs"
  max_log_files: 10
  log_file_max_size_mb: 50

# 数据处理配置
data_processing:
  chunk_size: 10000
  parse_dates_columns: ["ts"]
  handle_missing_values: true
  missing_value_strategy: "interpolate"
  enable_feature_selection: false

# 模型配置
model:
  kernel_type: "adaptive"
  alpha: 1e-10
  n_restarts_optimizer: 5
  validation_split: 0.2
  random_state: 42

# 部署配置
deployment:
  environment: "standard"
  enable_api_server: false
  enable_input_validation: true
  max_data_size_mb: 500