# 基准测试优化配置
# 专门用于性能基准测试和对比分析

benchmark:
  # 测试配置
  data_size_variants: [1000, 5000, 10000, 50000, 100000]
  feature_size_variants: [20, 50, 100, 200]
  model_variants: ["mlr", "hgbr", "gpr", "tcn", "transformer", "ensemble"]
  optimization_levels: ["baseline", "partial", "full"]
  
  # 运行设置
  n_runs_per_config: 5
  synthetic_data: true
  real_data_subset: true
  
  # 硬件配置
  target_gpus: ["rtx4060_8gb", "rtx3080_10gb", "rtx4090_24gb"]
  cpu_configs: [4, 8, 16]  # 核心数

models:
  mlr:
    baseline:
      fit_intercept: true
    optimized:
      fit_intercept: true
      copy_X: false  # 内存优化
  
  hgbr:
    baseline:
      max_iter: 100
      learning_rate: 0.1
    partial:
      max_iter: 200
      learning_rate: 0.1
      early_stopping: true
    full:
      max_iter: 500
      learning_rate: 0.08
      early_stopping: true
      validation_fraction: 0.1
  
  gpr:
    baseline:
      kernel: "rbf"
      alpha: 1e-6
    optimized:
      kernel: "rbf"
      alpha: 1e-6
      use_nystrom_approximation: true
      n_components: 512
  
  tcn:
    baseline:
      num_channels: [64, 64]
      kernel_size: 3
      dropout: 0.1
    optimized:
      num_channels: [128, 128, 128]
      kernel_size: 3
      dropout: 0.2
      use_linear_attention: true
  
  transformer:
    baseline:
      d_model: 64
      n_layers: 2
      n_heads: 4
    optimized:
      d_model: 128
      n_layers: 3
      n_heads: 4
      mixed_precision: true
      gradient_checkpointing: true

training:
  baseline:
    batch_size: 32
    learning_rate: 1e-3
    max_epochs: 50
    mixed_precision: false
    scheduler: "none"
  
  partial:
    batch_size: 64
    learning_rate: 5e-4
    max_epochs: 100
    mixed_precision: true
    scheduler: "step"
    early_stopping: true
  
  full:
    batch_size: 128
    gradient_accumulation_steps: 2
    learning_rate: 1e-3
    max_epochs: 200
    mixed_precision: true
    scheduler: "onecycle"
    early_stopping: true
    use_purged_validation: true
    gradient_checkpointing: true

preprocessing:
  baseline:
    normalization: "standard"
    outlier_removal: false
  
  partial:
    hampel_filter:
      window_size: 11
      threshold: 3.0
    normalization: "robust"
  
  full:
    hampel_filter:
      window_size: 11
      threshold: 3.0
      adaptive_threshold: true
    denoising:
      use_emd: true
      use_wavelet: true
    normalization: "robust"

features:
  baseline:
    window_sizes: [60]
    statistical_features: true
    frequency_features: false
  
  partial:
    window_sizes: [60, 180]
    statistical_features: true
    frequency_features: true
    dual_channel_selection: false
  
  full:
    window_sizes: [30, 60, 180]
    statistical_features: true
    frequency_features: true
    dual_channel_selection: true
    incremental_computation: true
    feature_caching: true

performance_metrics:
  # 准确性指标
  accuracy_metrics: ["r2_score", "rmse", "mae", "mape"]
  
  # 性能指标
  speed_metrics: ["training_time", "inference_time", "throughput"]
  
  # 资源指标
  resource_metrics: ["peak_memory", "gpu_memory", "cpu_utilization"]
  
  # 目标阈值
  targets:
    speed_improvement: 3.0
    memory_reduction: 0.4
    accuracy_maintenance: 0.95

reporting:
  # 报告生成
  generate_html_report: true
  generate_pdf_report: true
  generate_json_summary: true
  
  # 可视化
  performance_plots: true
  resource_usage_plots: true
  accuracy_comparison_plots: true
  
  # 对比分析
  baseline_comparison: true
  hardware_comparison: true
  scalability_analysis: true

output:
  results_dir: "benchmark_results"
  timestamp_suffix: true
  compress_results: true
  
logging:
  level: "INFO"
  log_file: "logs/benchmark.log"
  detailed_timing: true
  memory_tracking: true