# 大数据集优化配置（>100,000样本）
# HGBR + Local-SVGP + TCN+Attention全优化策略

model:
  type: "ensemble"
  models: ["hgbr", "local_svgp", "tcn_attention"]
  ensemble_method: "weighted_average"
  weights: [0.4, 0.3, 0.3]  # 基于验证性能动态调整
  
  hgbr:
    max_iter: 1000
    learning_rate: 0.05
    max_depth: 12
    min_samples_leaf: 50
    subsample: 0.8
    max_bins: 255
    early_stopping: true
    validation_fraction: 0.05
    n_iter_no_change: 50
    random_state: 42
  
  local_svgp:
    inducing_points: 2048
    kernel: "rbf"
    likelihood: "gaussian"
    variational_distribution: "cholesky"
    variational_strategy: "unwhitened"
    learn_inducing_locations: true
    jitter: 1e-4
  
  tcn_attention:
    # TCN配置
    num_channels: [128, 128, 128]
    kernel_size: 3
    dropout: 0.2
    
    # 线性注意力配置
    attention_dim: 64
    num_heads: 8
    use_linear_attention: true
    
    # 输出层
    output_dim: 1
    activation: "gelu"

training:
  # 大数据集训练设置
  batch_size: 256
  gradient_accumulation_steps: 2  # 等效batch_size=512
  mixed_precision: true
  gradient_checkpointing: true
  
  # 高级学习率调度
  learning_rate: 1e-3
  scheduler: "onecycle"
  onecycle_config:
    max_lr: 5e-3
    pct_start: 0.2
    div_factor: 25
    final_div_factor: 1000
    three_phase: true
  
  # 训练控制
  max_epochs: 200
  early_stopping_patience: 25
  validation_split: 0.15
  use_purged_validation: true
  purge_length: 15
  
  # 数据加载优化
  num_workers: 8
  pin_memory: true
  prefetch_factor: 4
  persistent_workers: true
  
  # 高级优化技术
  weight_decay: 1e-4
  gradient_clipping: true
  max_grad_norm: 1.0
  use_swa: true  # 随机权重平均
  swa_start: 150
  swa_lr: 1e-5

preprocessing:
  # 高性能预处理
  hampel_filter:
    window_size: 15
    threshold: 3.5
    adaptive_threshold: true
    parallel_processing: true
  
  denoising:
    use_emd: true
    emd_max_imfs: 12
    parallel_emd: true
    use_wavelet: true
    wavelet_type: "db6"
    soft_threshold: true
    
  normalization: "robust"
  outlier_removal: true
  outlier_method: "local_outlier_factor"
  
  # 数据增强
  augmentation: true
  noise_injection: 0.01
  time_warping: true

features:
  # 最大化特征工程
  dual_channel_selection: true
  feature_selection_method: "mutual_info_regression"
  max_features: 200
  
  vt_features:
    window_sizes: [15, 30, 60, 120, 180, 300]  # 多尺度窗口
    statistical_features: true
    frequency_features: true
    wavelet_features: true
    change_rate_features: true
    rolling_statistics: true
    incremental_computation: true
    parallel_computation: true
  
  vs_features:
    context_features: true
    time_encoding: true
    cyclic_encoding: true
    fourier_time_features: true
    setpoint_statistics: true
    equipment_ratings: true
    interaction_features: true
    polynomial_features: true
    degree: 2
  
  feature_caching: true
  cache_compression: true
  distributed_caching: true

performance_targets:
  min_r2_score: 0.85
  max_cv_rmse_percent: 4.0
  training_time_hours: 2
  inference_time_ms: 15
  peak_memory_gb: 6.0
  gpu_utilization_percent: 85

monitoring:
  system_monitoring: true
  sampling_interval: 0.5
  distributed_monitoring: true
  gpu_monitoring: true
  memory_profiling: true
  performance_profiling: true
  generate_reports: true
  visualization: true
  alert_thresholds:
    cpu_percent: 90
    memory_percent: 85
    gpu_memory_percent: 95

optimization:
  # 分布式训练（如果支持）
  distributed_training: false
  world_size: 1
  
  # 模型压缩
  model_compression: true
  quantization: "int8"
  pruning: true
  pruning_sparsity: 0.1
  
  # 推理优化
  inference_optimization: true
  tensorrt: false  # GPU推理加速
  onnx_export: true

logging:
  level: "INFO"
  log_file: "logs/large_dataset.log"
  console_output: true
  tensorboard: true
  wandb: true
  save_checkpoints: true
  checkpoint_frequency: 25
  keep_best_checkpoints: 5