# 中等数据集优化配置（10,000-100,000样本）
# HGBR + Nyström GPR混合策略

model:
  type: "hybrid"
  primary_model: "hgbr"
  uncertainty_model: "nystrom_gpr"
  
  hgbr:
    max_iter: 500
    learning_rate: 0.1
    max_depth: 10
    min_samples_leaf: 20
    max_bins: 255
    categorical_features: null
    monotonic_cst: null
    interaction_cst: null
    warm_start: false
    early_stopping: "auto"
    scoring: "loss"
    validation_fraction: 0.1
    n_iter_no_change: 20
    tol: 1e-7
    random_state: 42
  
  nystrom_gpr:
    kernel: "rbf"
    n_components: 1024
    gamma: null  # 自动估计
    random_state: 42
    kernel_params:
      length_scale: 1.0
      length_scale_bounds: [1e-2, 1e2]

training:
  # 中等数据集设置
  batch_size: 128
  gradient_accumulation_steps: 1
  mixed_precision: true
  
  # 学习率优化
  learning_rate: 5e-4
  scheduler: "cosine"
  cosine_scheduler:
    T_max: 80
    eta_min: 1e-6
    last_epoch: -1
  
  # 训练控制
  max_epochs: 80
  early_stopping_patience: 12
  validation_split: 0.2
  use_purged_validation: true
  purge_length: 8
  
  # 数据加载
  num_workers: 6
  pin_memory: true

preprocessing:
  # 标准预处理
  hampel_filter:
    window_size: 11
    threshold: 3.0
    adaptive_threshold: true
  
  denoising:
    use_emd: true
    emd_max_imfs: 8
    use_wavelet: true
    wavelet_type: "db4"
    soft_threshold: true
  
  normalization: "zscore"
  outlier_removal: true
  outlier_method: "isolation_forest"

features:
  # 全面特征工程
  dual_channel_selection: true
  vt_features:
    window_sizes: [30, 60, 120, 180]
    statistical_features: true
    frequency_features: true
    change_rate_features: true
    incremental_computation: true
  
  vs_features:
    context_features: true
    time_encoding: true
    cyclic_encoding: true
    setpoint_statistics: true
    equipment_ratings: true
    interaction_features: true
  
  feature_caching: true
  cache_compression: true

performance_targets:
  min_r2_score: 0.80
  max_cv_rmse_percent: 5.0
  training_time_minutes: 20
  inference_time_ms: 8
  memory_usage_gb: 4.0

monitoring:
  system_monitoring: true
  sampling_interval: 2.0
  memory_profiling: true
  generate_reports: true

logging:
  level: "INFO"
  log_file: "logs/medium_dataset.log"
  tensorboard: true
  save_checkpoints: true
  checkpoint_frequency: 10