# 生产环境优化配置
# 注重稳定性、可靠性和推理性能的生产就绪配置

model:
  type: "production"
  primary_model: "hgbr"  # 稳定可靠的基线模型
  fallback_model: "mlr"  # 故障时的后备模型
  
  hgbr:
    max_iter: 200  # 保守设置避免过拟合
    learning_rate: 0.08
    max_depth: 6
    min_samples_leaf: 20
    subsample: 0.9
    validation_fraction: 0.1
    early_stopping: true
    n_iter_no_change: 15
    tol: 1e-6
    random_state: 42
  
  mlr:
    fit_intercept: true
    copy_X: true
    positive: false

training:
  # 生产环境训练设置
  batch_size: 64
  mixed_precision: false  # 优先稳定性
  gradient_checkpointing: false
  
  # 保守学习率
  learning_rate: 1e-4
  scheduler: "step"
  step_scheduler:
    step_size: 30
    gamma: 0.8
  
  # 训练控制
  max_epochs: 100
  early_stopping_patience: 20
  validation_split: 0.2
  use_purged_validation: true
  purge_length: 10
  
  # 模型验证
  cross_validation: true
  cv_folds: 5
  cv_stratified: false

preprocessing:
  # 生产级预处理
  hampel_filter:
    window_size: 11
    threshold: 2.5  # 保守阈值
    adaptive_threshold: false
  
  denoising:
    use_emd: false  # 生产环境避免复杂处理
    use_wavelet: true
    wavelet_type: "db2"
    soft_threshold: true
  
  normalization: "robust"
  missing_value_strategy: "interpolation"
  outlier_handling: "clip"  # 截断而非移除

features:
  # 精选稳定特征
  dual_channel_selection: false
  vt_features:
    window_sizes: [60, 180]  # 稳定窗口大小
    statistical_features: true
    frequency_features: false
    incremental_computation: false
  
  vs_features:
    context_features: true
    time_encoding: true
    equipment_ratings: true
    interaction_features: false

performance_targets:
  min_r2_score: 0.75
  max_cv_rmse_percent: 6.0
  inference_time_ms: 5  # 快速推理
  model_size_mb: 10  # 轻量级模型
  reliability_score: 0.99

monitoring:
  # 生产监控
  system_monitoring: true
  sampling_interval: 5.0
  alert_enabled: true
  health_checks: true
  performance_tracking: true

reliability:
  # 可靠性设置
  model_validation: true
  input_validation: true
  output_validation: true
  confidence_intervals: true
  uncertainty_quantification: false
  
  # 故障处理
  error_handling: "graceful"
  fallback_prediction: "historical_average"
  retry_attempts: 3
  timeout_seconds: 30

deployment:
  # 部署配置
  batch_inference: true
  real_time_inference: true
  api_endpoint: true
  model_versioning: true
  a_b_testing: false

logging:
  level: "WARNING"  # 减少日志噪声
  log_file: "logs/production.log"
  log_rotation: true
  max_log_size_mb: 100
  backup_count: 5
  structured_logging: true