# RTX 4060 8GB 优化配置
# 针对8GB显存限制的混合精度训练优化方案

model:
  type: "adaptive"  # 自动选择最优模型架构
  
  # Transformer配置（大数据集）
  transformer:
    d_model: 128
    n_layers: 3
    n_heads: 4
    dropout: 0.1
    max_seq_length: 180
    use_linear_attention: true  # 内存优化

  # GPR配置（小数据集）
  gpr:
    kernel: "rbf"
    alpha: 1e-6
    use_nystrom_approximation: true
    n_components: 512

  # HGBR配置（中等数据集）
  hgbr:
    max_iter: 300
    learning_rate: 0.1
    max_depth: 8
    early_stopping: true
    validation_fraction: 0.1

training:
  # 内存优化设置
  batch_size: 64
  gradient_accumulation_steps: 2  # 等效batch_size=128
  mixed_precision: true
  gradient_checkpointing: true
  channels_last_memory_format: true
  
  # 学习率优化
  learning_rate: 3e-4
  scheduler: "onecycle"
  onecycle_config:
    max_lr: 3e-3
    pct_start: 0.3
    div_factor: 10
    final_div_factor: 100
  
  # 训练控制
  max_epochs: 100
  early_stopping_patience: 15
  validation_split: 0.2
  use_purged_validation: true
  purge_length: 10
  
  # 数据加载优化
  num_workers: 4
  pin_memory: true
  prefetch_factor: 2

preprocessing:
  # Hampel异常检测
  hampel_filter:
    window_size: 11
    threshold: 3.0
    adaptive_threshold: true
  
  # 多尺度去噪
  denoising:
    use_emd: true
    use_wavelet: true
    wavelet_type: "db4"
    soft_threshold: true
  
  # 数据标准化
  normalization: "zscore"
  robust_scaling: true

features:
  # 双通道特征选择
  dual_channel_selection: true
  vt_features:
    window_sizes: [30, 60, 180]  # 5分钟、10分钟、30分钟
    statistical_features: true
    frequency_features: true
    incremental_computation: true
  
  vs_features:
    context_features: true
    time_encoding: true
    setpoint_statistics: true
    equipment_ratings: true
  
  # 特征缓存
  feature_caching: true
  cache_compression: true

monitoring:
  # 系统监控
  system_monitoring: true
  sampling_interval: 1.0
  gpu_monitoring: true
  
  # 性能分析
  track_training_metrics: true
  track_inference_speed: true
  memory_profiling: true
  
  # 报告生成
  generate_reports: true
  visualization: true

hardware:
  # GPU优化
  target_gpu_memory_gb: 8.0
  memory_limit_safety_factor: 0.9  # 使用90%显存
  cuda_benchmark: true
  deterministic: false  # 性能优先
  
  # CPU优化
  max_cpu_cores: 8
  cpu_affinity: null  # 自动检测
  
  # 内存管理
  max_system_memory_gb: 16
  swap_usage_limit_percent: 10

performance_targets:
  # 速度目标
  training_speed_improvement: 3.0  # 3x提升
  inference_time_ms: 10  # <10ms推理
  
  # 内存目标
  memory_reduction_percent: 40  # 40%内存减少
  peak_gpu_memory_gb: 7.0  # <7GB显存使用
  
  # 准确性目标
  min_r2_score: 0.75
  max_cv_rmse_percent: 6.0
  accuracy_loss_tolerance_percent: 5.0

logging:
  level: "INFO"
  log_file: "logs/rtx4060_training.log"
  console_output: true
  tensorboard: false  # 节省显存
  wandb: false