# 小数据集优化配置（≤10,000样本）
# MLR + Exact GPR残差建模策略

model:
  type: "residual"
  primary_model: "mlr"
  residual_model: "exact_gpr"
  
  mlr:
    fit_intercept: true
    copy_X: true
    normalize: false  # 已在预处理中标准化
  
  gpr:
    kernel: "rbf"
    kernel_params:
      length_scale: 1.0
      length_scale_bounds: [1e-5, 1e2]
    alpha: 1e-6
    optimizer: "fmin_l_bfgs_b"
    normalize_y: false
    copy_X_train: true
    random_state: 42

training:
  # 小数据集设置
  batch_size: 32
  mixed_precision: false  # 小数据集不需要
  
  # 学习率设置
  learning_rate: 1e-3
  scheduler: "step"
  step_scheduler:
    step_size: 20
    gamma: 0.5
  
  # 训练控制
  max_epochs: 50
  early_stopping_patience: 10
  validation_split: 0.25  # 更多验证数据
  use_purged_validation: true
  purge_length: 5
  
  # 交叉验证
  cross_validation: true
  cv_folds: 5
  cv_scoring: ["r2", "neg_mean_squared_error"]

preprocessing:
  # 轻量级预处理
  hampel_filter:
    window_size: 7
    threshold: 2.5
  
  denoising:
    use_emd: false  # 小数据集跳过EMD
    use_wavelet: true
    wavelet_type: "db2"
  
  normalization: "robust"  # 对异常值更鲁棒

features:
  # 精简特征工程
  dual_channel_selection: false
  vt_features:
    window_sizes: [30, 60]  # 减少窗口数量
    statistical_features: true
    frequency_features: false  # 小数据集跳过频域特征
    incremental_computation: false
  
  vs_features:
    context_features: true
    time_encoding: false  # 简化时间编码
    equipment_ratings: true

performance_targets:
  min_r2_score: 0.70
  max_cv_rmse_percent: 8.0
  training_time_minutes: 5
  inference_time_ms: 5

logging:
  level: "DEBUG"  # 详细日志用于调试
  log_file: "logs/small_dataset.log"